name: 'Campfire Notification Action - Basecamp'
description: 'A GitHub action that enables workflows to send messages directly to a Basecamp-Campfire chat.'
inputs:
  account_id:
    description: 'Basecamp account ID'
    required: true
    default: ''
  bucket_id:
    description: 'Basecamp bucket ID'
    required: true
    default: ''
  chat_id:
    description: 'Basecamp chat ID'
    required: true
    default: ''
  message:
    description: 'Message to send'
    required: true
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'