name: 'Campfire Notification Action - Basecamp'
description: 'A GitHub action that enables workflows to send messages directly to a Basecamp-Campfire chat. It leverages Basecamp's bot chat functionality, eliminating the need for OAuth authentication. Ideal for teams looking to enhance their workflow with real-time GitHub updates in their Basecamp-Campfire chats.'
inputs:
  account_id:
    description: 'Basecamp account ID'
    required: true
    default: ''
  bucket_id:
    description: 'Basecamp bucket ID'
    required: true
    default: ''
  chat_id:
    description: 'Basecamp chat ID'
    required: true
    default: ''
  message:
    description: 'Message to send'
    required: true
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'